# Generated by Django 6.0.5 on 2026-05-27 03:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('ADMIN', 'Admin'), ('AUDITOR', 'Auditor')], default='ANALYST', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='esg.tenant')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=16)),
                ('variant_tag', models.CharField(blank=True, max_length=64)),
                ('column_mappings', models.JSONField(default=dict)),
                ('unit_mappings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_mappings', to='esg.tenant')),
            ],
            options={
                'db_table': 'source_mapping',
            },
        ),
        migrations.CreateModel(
            name='SourceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel/Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=16)),
                ('original_filename', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PARTIAL', 'Partial (some rows failed)'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('row_count_total', models.IntegerField(blank=True, null=True)),
                ('row_count_success', models.IntegerField(blank=True, null=True)),
                ('row_count_failed', models.IntegerField(blank=True, null=True)),
                ('row_count_suspicious', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='esg.sourcemapping')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='esg.tenant')),
            ],
            options={
                'db_table': 'source_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='esg.sourceupload')),
            ],
            options={
                'db_table': 'raw_record',
            },
        ),
        migrations.CreateModel(
            name='PlantCodeLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=32)),
                ('plant_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('grid_region', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_codes', to='esg.tenant')),
            ],
            options={
                'db_table': 'plant_code_lookup',
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct'), (2, 'Scope 2 - Purchased Energy'), (3, 'Scope 3 - Value Chain')])),
                ('emission_category', models.CharField(choices=[('STATIONARY_COMBUSTION', 'Stationary Combustion'), ('MOBILE_COMBUSTION', 'Mobile Combustion'), ('PURCHASED_ELECTRICITY', 'Purchased Electricity'), ('BUSINESS_TRAVEL_AIR', 'Business Travel - Air'), ('BUSINESS_TRAVEL_RAIL', 'Business Travel - Rail'), ('BUSINESS_TRAVEL_HOTEL', 'Business Travel - Hotel'), ('BUSINESS_TRAVEL_GROUND', 'Business Travel - Ground')], max_length=64)),
                ('activity_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('activity_unit', models.CharField(choices=[('kWh', 'Kilowatt-hours'), ('MWh', 'Megawatt-hours'), ('L', 'Liters'), ('m3', 'Cubic Meters'), ('km', 'Kilometers'), ('pkm', 'Passenger-kilometers'), ('nights', 'Nights (hotel)')], max_length=16)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=32)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=128)),
                ('co2e_tonnes', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_entity_id', models.CharField(blank=True, max_length=128)),
                ('source_entity_name', models.CharField(blank=True, max_length=255)),
                ('origin_code', models.CharField(blank=True, max_length=8)),
                ('destination_code', models.CharField(blank=True, max_length=8)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_is_estimated', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged - Suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False)),
                ('suspicious_reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='esg.normalizedemissionrecord')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized', to='esg.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='esg.tenant')),
            ],
            options={
                'db_table': 'normalized_emission_record',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOAD_CREATED', 'Upload Created'), ('UPLOAD_PROCESSING', 'Upload Processing Started'), ('UPLOAD_COMPLETE', 'Upload Complete'), ('UPLOAD_FAILED', 'Upload Failed'), ('RECORD_CREATED', 'Record Created'), ('RECORD_FLAGGED', 'Record Flagged as Suspicious'), ('RECORD_APPROVED', 'Record Approved'), ('RECORD_REJECTED', 'Record Rejected'), ('RECORD_LOCKED', 'Record Locked for Audit'), ('RECORD_SUPERSEDED', 'Record Superseded by Correction'), ('MAPPING_UPDATED', 'Source Mapping Updated'), ('PLANT_CODE_ADDED', 'Plant Code Lookup Added')], max_length=32)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='esg.tenant')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['upload', 'row_number'], name='raw_record_upload__79afd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('upload', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='sourceupload',
            index=models.Index(fields=['tenant', 'source_type', '-created_at'], name='source_uplo_tenant__880e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceupload',
            index=models.Index(fields=['file_hash'], name='source_uplo_file_ha_1e1184_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'source_type', 'variant_tag'), name='unique_active_mapping_per_source'),
        ),
        migrations.AlterUniqueTogether(
            name='plantcodelookup',
            unique_together={('tenant', 'plant_code')},
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'review_status'], name='normalized__tenant__3e034f_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['tenant', 'emission_category', '-period_start'], name='normalized__tenant__ad5002_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['is_suspicious', 'review_status'], name='normalized__is_susp_cf5e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['is_locked'], name='normalized__is_lock_930d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', '-created_at'], name='audit_log_tenant__dfd678_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_log_actor_i_91cd96_idx'),
        ),
    ]
